// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chat_msg.proto

/*
Package chat_msg is a generated protocol buffer package.

It is generated from these files:
	chat_msg.proto

It has these top-level messages:
	ChatMsg
*/
package chat_msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ChatMsg struct {
	Name    string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *ChatMsg) Reset()                    { *m = ChatMsg{} }
func (m *ChatMsg) String() string            { return proto.CompactTextString(m) }
func (*ChatMsg) ProtoMessage()               {}
func (*ChatMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ChatMsg) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ChatMsg) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*ChatMsg)(nil), "chat_msg.ChatMsg")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Chat service

type ChatClient interface {
	DoChat(ctx context.Context, opts ...grpc.CallOption) (Chat_DoChatClient, error)
}

type chatClient struct {
	cc *grpc.ClientConn
}

func NewChatClient(cc *grpc.ClientConn) ChatClient {
	return &chatClient{cc}
}

func (c *chatClient) DoChat(ctx context.Context, opts ...grpc.CallOption) (Chat_DoChatClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Chat_serviceDesc.Streams[0], c.cc, "/chat_msg.Chat/DoChat", opts...)
	if err != nil {
		return nil, err
	}
	x := &chatDoChatClient{stream}
	return x, nil
}

type Chat_DoChatClient interface {
	Send(*ChatMsg) error
	Recv() (*ChatMsg, error)
	grpc.ClientStream
}

type chatDoChatClient struct {
	grpc.ClientStream
}

func (x *chatDoChatClient) Send(m *ChatMsg) error {
	return x.ClientStream.SendMsg(m)
}

func (x *chatDoChatClient) Recv() (*ChatMsg, error) {
	m := new(ChatMsg)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Chat service

type ChatServer interface {
	DoChat(Chat_DoChatServer) error
}

func RegisterChatServer(s *grpc.Server, srv ChatServer) {
	s.RegisterService(&_Chat_serviceDesc, srv)
}

func _Chat_DoChat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChatServer).DoChat(&chatDoChatServer{stream})
}

type Chat_DoChatServer interface {
	Send(*ChatMsg) error
	Recv() (*ChatMsg, error)
	grpc.ServerStream
}

type chatDoChatServer struct {
	grpc.ServerStream
}

func (x *chatDoChatServer) Send(m *ChatMsg) error {
	return x.ServerStream.SendMsg(m)
}

func (x *chatDoChatServer) Recv() (*ChatMsg, error) {
	m := new(ChatMsg)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Chat_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chat_msg.Chat",
	HandlerType: (*ChatServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DoChat",
			Handler:       _Chat_DoChat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "chat_msg.proto",
}

func init() { proto.RegisterFile("chat_msg.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 141 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0xce, 0x48, 0x2c,
	0x89, 0xcf, 0x2d, 0x4e, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0xf1, 0x95, 0xcc,
	0xb9, 0xd8, 0x9d, 0x33, 0x12, 0x4b, 0x7c, 0x8b, 0xd3, 0x85, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73,
	0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x21, 0x09, 0x2e, 0xf6, 0xdc, 0xd4,
	0xe2, 0xe2, 0xc4, 0xf4, 0x54, 0x09, 0x26, 0xb0, 0x30, 0x8c, 0x6b, 0x64, 0xc3, 0xc5, 0x02, 0xd2,
	0x28, 0x64, 0xc2, 0xc5, 0xe6, 0x92, 0x0f, 0x66, 0x09, 0xea, 0xc1, 0x6d, 0x81, 0x1a, 0x29, 0x85,
	0x29, 0xa4, 0xc4, 0xa0, 0xc1, 0x68, 0xc0, 0xe8, 0x24, 0xcd, 0xc5, 0x97, 0x9e, 0x0f, 0x92, 0x03,
	0x2b, 0xf0, 0x2d, 0x4e, 0x77, 0x82, 0x39, 0x23, 0x80, 0x31, 0x89, 0x0d, 0xec, 0x48, 0x63, 0x40,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xc0, 0x93, 0x5a, 0xfd, 0xb6, 0x00, 0x00, 0x00,
}
